service: serverless-aws-lambda-ts-examples

#s3:
#  bucket: serverless-aws-lambda-ts-examples-s3-bucket

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-east-1
  memorySize: 128
  timeout: 30

# you can add packaging information here
# package:
#  include:
#    - node_modules
#  exclude:
#    - package.json
#  artifact: my-service-code.zip

functions:
  serverlessAWSLambdaTS:
    handler: bundle.handleIt
#    environment:
#      BUCKET: ${self:s3.bucket}

#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-webpack
